# Generated by Django 5.2.9 on 2025-12-26 16:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('caracteristiques', models.TextField(blank=True, default='')),
                ('prix_achat_unitaire_euro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('categorie', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_initial', models.PositiveIntegerField(default=0)),
                ('quantite_vendue', models.PositiveIntegerField(default=0)),
                ('quantite_restante', models.PositiveIntegerField(default=0)),
                ('quantite_pretee', models.PositiveIntegerField(default=0)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.produit')),
            ],
            options={
                'ordering': ['produit__nom', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TauxChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_euro_cfa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_application', models.DateField(default=django.utils.timezone.localdate)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taux_change', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_application', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('achat', 'Achat'), ('vente', 'Vente'), ('pret', 'Prêt'), ('retour', 'Retour')], max_length=20)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire_euro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_unitaire_cfa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taux_change', models.DecimalField(blank=True, decimal_places=2, help_text='Taux EUR -> CFA appliqué à cette transaction', max_digits=10, null=True)),
                ('date_transaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_fournisseur', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.produit')),
            ],
            options={
                'ordering': ['-date_transaction', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Dette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=200)),
                ('quantite_pretee', models.PositiveIntegerField()),
                ('date_pret', models.DateField(default=django.utils.timezone.localdate)),
                ('date_retour_prevue', models.DateField(blank=True, null=True)),
                ('date_retour_effective', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('retourne', 'Retourné'), ('retard', 'En retard')], default='en_cours', max_length=20)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dettes', to='inventory.produit')),
                ('transaction_pret', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dette_pret', to='inventory.transaction')),
                ('transaction_retour', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dette_retour', to='inventory.transaction')),
            ],
            options={
                'ordering': ['-date_pret', '-id'],
            },
        ),
    ]
